{% set name = "ldblockshow" %}
{% set version = "1.30" %}
{% set sha256 = "4f0d445e304b9cef232be7bf61ba6acd202b331312719df8804926d93ad4cc8c" %}

package:
  name: {{ name }}
  version: {{ version }}

build:
  number: 0

source:
  url: https://github.com/BGI-shenzhen/LDBlockShow/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - perl
    - zlib
  run:
    - perl-svg
    - plink
    - zlib

about:
  home: https://github.com/BGI-shenzhen/LDBlockShow
  license: MIT
  license_file: LICENSE
  summary: a tool for showing linkage disequilibrium heatmaps from variant call format (VCF) files

test:
  commands:
    - "LDBlockShow 2>&1 | grep 'Usage: LDBlockShow'"

extra:
  identifiers:
    - biotools:ldblockshow
