{% set name = "gxformat2" %}
{% set version = "0.11.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 14cd529791b4cd1ed9cc8027c5ca8bf875a78f692b2b6b27de5f306a3507b98f

build:
  number: 0
  noarch: python
  preserve_egg_dir: True
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pyyaml
    - bioblend
    - six >=1.9.0

test:
  imports:
    - gxformat2

about:
  home: https://github.com/jmchilton/gxformat2
  license: AFL-3.0-only
  summary: 'Galaxy Workflow Format 2 Descriptions'
  license_family: OTHER
